<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: publisher_prefix_list.proto

namespace Publishers_pb\PublisherPrefixList;

use UnexpectedValueException;

/**
 * Protobuf type <code>publishers_pb.PublisherPrefixList.CompressionType</code>
 */
class CompressionType
{
    /**
     * Generated from protobuf enum <code>NO_COMPRESSION = 0;</code>
     */
    const NO_COMPRESSION = 0;
    /**
     * Generated from protobuf enum <code>BROTLI_COMPRESSION = 1;</code>
     */
    const BROTLI_COMPRESSION = 1;

    private static $valueToName = [
        self::NO_COMPRESSION => 'NO_COMPRESSION',
        self::BROTLI_COMPRESSION => 'BROTLI_COMPRESSION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CompressionType::class, \Publishers_pb\PublisherPrefixList_CompressionType::class);

