<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: channel_response.proto

namespace Publishers_pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>publishers_pb.ChannelResponseList</code>
 */
class ChannelResponseList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .publishers_pb.ChannelResponse channel_responses = 1;</code>
     */
    private $channel_responses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Publishers_pb\ChannelResponse[]|\Google\Protobuf\Internal\RepeatedField $channel_responses
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ChannelResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .publishers_pb.ChannelResponse channel_responses = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChannelResponses()
    {
        return $this->channel_responses;
    }

    /**
     * Generated from protobuf field <code>repeated .publishers_pb.ChannelResponse channel_responses = 1;</code>
     * @param \Publishers_pb\ChannelResponse[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChannelResponses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Publishers_pb\ChannelResponse::class);
        $this->channel_responses = $arr;

        return $this;
    }

}

