<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: publisher_prefix_list.proto

namespace Publishers_pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>publishers_pb.PublisherPrefixList</code>
 */
class PublisherPrefixList extends \Google\Protobuf\Internal\Message
{
    /**
     * The size, in bytes, of each hash prefix stored in the
     * prefix list. This value must be between 4 and 32.
     *
     * Generated from protobuf field <code>uint32 prefix_size = 1;</code>
     */
    protected $prefix_size = 0;
    /**
     * The type of compression applied to the hash prefix list.
     *
     * Generated from protobuf field <code>.publishers_pb.PublisherPrefixList.CompressionType compression_type = 2;</code>
     */
    protected $compression_type = 0;
    /**
     * The uncompressed size, in bytes, of the hash prefix list.
     *
     * Generated from protobuf field <code>uint32 uncompressed_size = 3;</code>
     */
    protected $uncompressed_size = 0;
    /**
     * A sorted list of fixed-length prefixes of SHA256 hashes
     * corresponding to each publisher.
     *
     * Generated from protobuf field <code>bytes prefixes = 4;</code>
     */
    protected $prefixes = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $prefix_size
     *           The size, in bytes, of each hash prefix stored in the
     *           prefix list. This value must be between 4 and 32.
     *     @type int $compression_type
     *           The type of compression applied to the hash prefix list.
     *     @type int $uncompressed_size
     *           The uncompressed size, in bytes, of the hash prefix list.
     *     @type string $prefixes
     *           A sorted list of fixed-length prefixes of SHA256 hashes
     *           corresponding to each publisher.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PublisherPrefixList::initOnce();
        parent::__construct($data);
    }

    /**
     * The size, in bytes, of each hash prefix stored in the
     * prefix list. This value must be between 4 and 32.
     *
     * Generated from protobuf field <code>uint32 prefix_size = 1;</code>
     * @return int
     */
    public function getPrefixSize()
    {
        return $this->prefix_size;
    }

    /**
     * The size, in bytes, of each hash prefix stored in the
     * prefix list. This value must be between 4 and 32.
     *
     * Generated from protobuf field <code>uint32 prefix_size = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPrefixSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->prefix_size = $var;

        return $this;
    }

    /**
     * The type of compression applied to the hash prefix list.
     *
     * Generated from protobuf field <code>.publishers_pb.PublisherPrefixList.CompressionType compression_type = 2;</code>
     * @return int
     */
    public function getCompressionType()
    {
        return $this->compression_type;
    }

    /**
     * The type of compression applied to the hash prefix list.
     *
     * Generated from protobuf field <code>.publishers_pb.PublisherPrefixList.CompressionType compression_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCompressionType($var)
    {
        GPBUtil::checkEnum($var, \Publishers_pb\PublisherPrefixList\CompressionType::class);
        $this->compression_type = $var;

        return $this;
    }

    /**
     * The uncompressed size, in bytes, of the hash prefix list.
     *
     * Generated from protobuf field <code>uint32 uncompressed_size = 3;</code>
     * @return int
     */
    public function getUncompressedSize()
    {
        return $this->uncompressed_size;
    }

    /**
     * The uncompressed size, in bytes, of the hash prefix list.
     *
     * Generated from protobuf field <code>uint32 uncompressed_size = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUncompressedSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->uncompressed_size = $var;

        return $this;
    }

    /**
     * A sorted list of fixed-length prefixes of SHA256 hashes
     * corresponding to each publisher.
     *
     * Generated from protobuf field <code>bytes prefixes = 4;</code>
     * @return string
     */
    public function getPrefixes()
    {
        return $this->prefixes;
    }

    /**
     * A sorted list of fixed-length prefixes of SHA256 hashes
     * corresponding to each publisher.
     *
     * Generated from protobuf field <code>bytes prefixes = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPrefixes($var)
    {
        GPBUtil::checkString($var, False);
        $this->prefixes = $var;

        return $this;
    }

}
