<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: publisher_prefix_list.proto

namespace Publishers_pb;

if (false) {
    /**
     * This class is deprecated. Use Publishers_pb\PublisherPrefixList\CompressionType instead.
     * @deprecated
     */
    class PublisherPrefixList_CompressionType {}
}
class_exists(PublisherPrefixList\CompressionType::class);
@trigger_error('Publishers_pb\PublisherPrefixList_CompressionType is deprecated and will be removed in the next major release. Use Publishers_pb\PublisherPrefixList\CompressionType instead', E_USER_DEPRECATED);

