<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: channel_response.proto

namespace Publishers_pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>publishers_pb.SiteBannerDetails</code>
 */
class SiteBannerDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string title = 1;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string background_url = 3;</code>
     */
    protected $background_url = '';
    /**
     * Generated from protobuf field <code>string logo_url = 4;</code>
     */
    protected $logo_url = '';
    /**
     * Generated from protobuf field <code>repeated double donation_amounts = 5;</code>
     */
    private $donation_amounts;
    /**
     * Generated from protobuf field <code>.publishers_pb.SocialLinks social_links = 6;</code>
     */
    protected $social_links = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *     @type string $description
     *     @type string $background_url
     *     @type string $logo_url
     *     @type float[]|\Google\Protobuf\Internal\RepeatedField $donation_amounts
     *     @type \Publishers_pb\SocialLinks $social_links
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ChannelResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string background_url = 3;</code>
     * @return string
     */
    public function getBackgroundUrl()
    {
        return $this->background_url;
    }

    /**
     * Generated from protobuf field <code>string background_url = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBackgroundUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->background_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string logo_url = 4;</code>
     * @return string
     */
    public function getLogoUrl()
    {
        return $this->logo_url;
    }

    /**
     * Generated from protobuf field <code>string logo_url = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLogoUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->logo_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated double donation_amounts = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDonationAmounts()
    {
        return $this->donation_amounts;
    }

    /**
     * Generated from protobuf field <code>repeated double donation_amounts = 5;</code>
     * @param float[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDonationAmounts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->donation_amounts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.publishers_pb.SocialLinks social_links = 6;</code>
     * @return \Publishers_pb\SocialLinks
     */
    public function getSocialLinks()
    {
        return isset($this->social_links) ? $this->social_links : null;
    }

    public function hasSocialLinks()
    {
        return isset($this->social_links);
    }

    public function clearSocialLinks()
    {
        unset($this->social_links);
    }

    /**
     * Generated from protobuf field <code>.publishers_pb.SocialLinks social_links = 6;</code>
     * @param \Publishers_pb\SocialLinks $var
     * @return $this
     */
    public function setSocialLinks($var)
    {
        GPBUtil::checkMessage($var, \Publishers_pb\SocialLinks::class);
        $this->social_links = $var;

        return $this;
    }

}

