<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: channel_response.proto

namespace Publishers_pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>publishers_pb.SocialLinks</code>
 */
class SocialLinks extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string youtube = 1;</code>
     */
    protected $youtube = '';
    /**
     * Generated from protobuf field <code>string twitter = 2;</code>
     */
    protected $twitter = '';
    /**
     * Generated from protobuf field <code>string twitch = 3;</code>
     */
    protected $twitch = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $youtube
     *     @type string $twitter
     *     @type string $twitch
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ChannelResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string youtube = 1;</code>
     * @return string
     */
    public function getYoutube()
    {
        return $this->youtube;
    }

    /**
     * Generated from protobuf field <code>string youtube = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setYoutube($var)
    {
        GPBUtil::checkString($var, True);
        $this->youtube = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string twitter = 2;</code>
     * @return string
     */
    public function getTwitter()
    {
        return $this->twitter;
    }

    /**
     * Generated from protobuf field <code>string twitter = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTwitter($var)
    {
        GPBUtil::checkString($var, True);
        $this->twitter = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string twitch = 3;</code>
     * @return string
     */
    public function getTwitch()
    {
        return $this->twitch;
    }

    /**
     * Generated from protobuf field <code>string twitch = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTwitch($var)
    {
        GPBUtil::checkString($var, True);
        $this->twitch = $var;

        return $this;
    }

}

