<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: channel_response.proto

namespace Publishers_pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>publishers_pb.Wallet</code>
 */
class Wallet extends \Google\Protobuf\Internal\Message
{
    protected $provider;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Publishers_pb\UpholdWallet $uphold_wallet
     *     @type \Publishers_pb\PaypalWallet $paypal_wallet
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ChannelResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.publishers_pb.UpholdWallet uphold_wallet = 1;</code>
     * @return \Publishers_pb\UpholdWallet
     */
    public function getUpholdWallet()
    {
        return $this->readOneof(1);
    }

    public function hasUpholdWallet()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.publishers_pb.UpholdWallet uphold_wallet = 1;</code>
     * @param \Publishers_pb\UpholdWallet $var
     * @return $this
     */
    public function setUpholdWallet($var)
    {
        GPBUtil::checkMessage($var, \Publishers_pb\UpholdWallet::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.publishers_pb.PaypalWallet paypal_wallet = 2;</code>
     * @return \Publishers_pb\PaypalWallet
     */
    public function getPaypalWallet()
    {
        return $this->readOneof(2);
    }

    public function hasPaypalWallet()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.publishers_pb.PaypalWallet paypal_wallet = 2;</code>
     * @param \Publishers_pb\PaypalWallet $var
     * @return $this
     */
    public function setPaypalWallet($var)
    {
        GPBUtil::checkMessage($var, \Publishers_pb\PaypalWallet::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getProvider()
    {
        return $this->whichOneof("provider");
    }

}

