<?php

return [
    'heartbeat' => 'http://beats.envoyer.io/heartbeat/hNLvIxNdSHEosAG',
    'admin_email' => 'songhua@gmail.com',
    'transparency_page' => 'https://brave.com/transparency/',
    'referral_link' => 'https://brave.com/?ref=iuv633',
    's3' => "https://bravebat-prod.s3.us-west-2.amazonaws.com/",
    'catelog_page' => [
        'v3' => "https://ads-serve.brave.com/v3/catalog",
        'v7' => "https://ads-serve.brave.com/v7/catalog",
        'proxy' => "https://proxy.bravebat.info",
    ],
    "brave_prefix_list_url" => 'https://rewards.brave.com/publishers/prefix-list',
    "brave_prefix_channel_url" => 'https://pcdn.brave.com/publishers/prefixes/',
    'colors' => [
        '#fb542b',
        '#4299e1',
        '#667eea',
        '#9f7aea',
        '#ed64a6',
        '#a0aec0',
        '#f56565',
        '#ed8936',
        '#ecc94b',
        '#48bb78',
        '#38b2ac',
        '#90cdf4',
        '#a3bffa',
        '#d6bcfa',
        '#fbb6ce',
        '#e2e8f0',
        '#feb2b2',
        '#fbd38d',
        '#faf089',
        '#9ae6b4',
        '#81e6d9',
    ],
    'creator_brand_colors' => [
        'youtube' => '#ff0000',
        'reddit' => '#ff4500',
        'twitch' => '#6441a5',
        'vimeo' => '#1ab7ea',
        'github' => '#4078c0',
        'twitter' => '#1da1f2',
        'website' => '#343546',
    ],
    "top_creators_cutoff" => [
        'youtube' => 1000000,
        'twitter' => 1000000,
        'twitch' => 100000,
        'vimeo' => 1000,
        'github' => 1000,
        'website' => 1000,
    ],
    'communities' => [
        'reddit' => [
            'brave_browser' => 'brave_browser',
            'batproject' => 'batproject',
        ],
        'telegram' => [
            'batproject' => 'batproject',
        ],
        'twitter' => [
            'brave' => '257245904',
            'attentiontoken' => '841424245938769920',
            'bat_community' => '984525722000744448',
        ],
        'youtube' => [
            'bravesoftware' => 'UCFNTTISby1c_H-rm5Ww5rZg',
        ],
    ],
    'channels' => [
        'youtube',
        'twitter',
        'twitch',
        'vimeo',
        'github',
        'website',
        'reddit',
    ],
];
