<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/Services/Support/example.proto

namespace GPBMetadata\App\Services\Support;

class Example
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Q
"app/Services/Support/example.protofoo.bar"
	MyMessage
title (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

